version: 2

sources:
  - name: raw
    database: KS_DB
    schema: raw
    tables:
      - name: sales_events

  - name: marts
    database: KS_DB
    schema: marts
    tables:
      - name: predictions